In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from adjustText import adjust_text
from matplotlib.patches import Circle
import os
import pickle
from scipy.stats import mannwhitneyu, ttest_ind, kruskal, f_oneway
from statannotations.Annotator import Annotator
from itertools import combinations
from ipywidgets import interact
import ipywidgets as widgets
from IPython.display import clear_output, display

In [3]:
df_food_scaled = pd.read_csv('df_food_scaled.csv')

C:\Users\Sophie\AppData\Local\Temp\ipykernel_1948\4074791732.py:1: DtypeWarning: Columns (1,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_food_scaled = pd.read_csv('df_food_scaled.csv')

In [4]:
df_alcoholic_beverages = df_food_scaled[df_food_scaled['food_group'] == 'alcoholic_beverages']
df_alcoholic_beverages.drop_duplicates('combined_name')[['combined_name', 'QI', 'DI', 'NB']].sort_values('QI', ascending=False)

                    combined_name         QI        DI         NB
307939                  Spirtonic  11.238290  0.373402  10.000000
300255                 Coop Ilios   1.115954  2.192502  56.060904
298432            Hite Pale lager   0.981281  0.258626  10.000000
198504                   Spritzer   0.813986  0.645044  56.856483
302341  Appenzeller bier bschorle   0.813986  0.645044  56.856483
...                           ...        ...       ...        ...
317140         Calanda - Edelbräu   0.000000  0.000000   0.000000
317359       1664 - Bière blanche   0.000000  0.000000   0.000000
317553   Eichhof - Radler Zitrone   0.000000  0.000000   0.000000
317647   Feldschlösschen - Märzen   0.000000  0.000000   0.000000
317688          Feldschlössen IPA   0.000000  0.000000   0.000000

[421 rows x 4 columns]

In [5]:
df_alcoholic_beverages[df_alcoholic_beverages['combined_name'] == 'Spirtonic'].drop_duplicates('combined_name')[[i for i in df_alcoholic_beverages.columns if '_ratio_scaled' in i]].T

                                                        307939
folate_eaten_ratio_scaled                             0.000000
niacin_eaten_ratio_scaled                             0.000000
pantothenic_acid_eaten_ratio_scaled                   0.000000
vitamin_b2_eaten_ratio_scaled                         0.000000
vitamin_b1_eaten_ratio_scaled                         0.000000
all_trans_retinol_equivalents_activity_eaten_ra...    0.000000
beta_carotene_eaten_ratio_scaled                      0.000000
vitamin_b12_eaten_ratio_scaled                        0.000000
vitamin_b6_eaten_ratio_scaled                         0.000000
vitamin_c_eaten_ratio_scaled                        220.994475
vitamin_d_eaten_ratio_scaled                          0.000000
vitamin_e_activity_eaten_ratio_scaled                 0.000000
calcium_eaten_ratio_scaled                            0.000000
iron_eaten_ratio_scaled                               0.000000
magnesium_eaten_ratio_scaled                          0.000000
phosphorus_eaten_ratio_scaled                         0.000000
potassium_eaten_ratio_scaled                          0.000000
zinc_eaten_ratio_scaled                               0.000000
fiber_eaten_ratio_scaled                              0.000000
protein_eaten_ratio_scaled                            3.771319
fat_eaten_ratio_scaled                                0.247910
fatty_acids_saturated_eaten_ratio_scaled              0.226017
cholesterol_eaten_ratio_scaled                        0.000000
sugar_eaten_ratio_scaled                              0.477348
sodium_eaten_ratio_scaled                             0.000000
salt_eaten_ratio_scaled                               1.289134

- vitamin c